GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Go to play football"
}

###

DELETE http://localhost:3001/todo/delete/636020897d99b4f1b2fa910e

###

PUT http://localhost:3001/todo/complete/636020c27d99b4f1b2fa9110